import { Router } from 'express';
import { z } from 'zod';
import { authenticate, requirePermission } from '../../middleware/auth.js';
import { asyncHandler } from '../../utils/async-handler.js';
import { ApiError } from '../../utils/api-error.js';
import { ok } from '../../utils/api-response.js';
import { pagination } from '../../utils/pagination.js';
import { audit } from '../audit/audit.service.js';
import { Employee } from '../employees/employee.model.js';
import { EmployeeLifecycleEvent, HrPolicy, Notification, ProbationEvaluation, TraineeType } from './lifecycle.model.js';
import { addUtcMonths, getHrPolicy, lifecycleEvent, reminderStatus, runEmployeeLifecycleReminderJobs } from './lifecycle.service.js';

export const lifecycleRouter = Router(); lifecycleRouter.use(authenticate);
const hrRoles = ['SUPER_ADMIN', 'HR_ADMIN', 'HR'];

lifecycleRouter.get('/trainee-types', asyncHandler(async (request, response) => { const filter = request.query.all === 'true' && ['SUPER_ADMIN', 'HR_ADMIN'].includes(request.auth!.role) ? {} : { isActive: true }; ok(response, await TraineeType.find(filter).sort({ name: 1 })); }));
lifecycleRouter.post('/trainee-types', requirePermission('trainee:manage'), asyncHandler(async (request, response) => { const input = z.object({ name: z.string().min(2).max(100), code: z.string().min(2).max(30), description: z.string().max(500).optional(), isActive: z.boolean().default(true) }).parse(request.body); const item = await TraineeType.create(input); await audit(request, 'TRAINEE_TYPE_CREATED', 'TraineeType', item._id, input); ok(response, item, undefined, 201); }));

lifecycleRouter.get('/policy', requirePermission('employee:type:manage'), asyncHandler(async (_request, response) => ok(response, await getHrPolicy())));
lifecycleRouter.put('/policy', requirePermission('employee:type:manage'), asyncHandler(async (request, response) => { const input = z.object({ probationDurationMonths: z.number().int().min(1).max(36), probationEvaluationReminderDays: z.number().int().min(0).max(180), contractExpiryReminderDays: z.number().int().min(0).max(365), traineeCompletionReminderDays: z.number().int().min(0).max(180), timezone: z.string().min(3).max(80) }).parse(request.body); try { new Intl.DateTimeFormat('en', { timeZone: input.timezone }); } catch { throw new ApiError(422, 'Invalid IANA timezone', 'INVALID_TIMEZONE'); } const policy = await HrPolicy.findOneAndUpdate({ key: 'DEFAULT' }, { ...input, key: 'DEFAULT' }, { upsert: true, new: true, runValidators: true }); await audit(request, 'HR_POLICY_UPDATED', 'HrPolicy', policy._id, input); ok(response, policy); }));

lifecycleRouter.post('/reminders/run', requirePermission('notification:hr:view'), asyncHandler(async (request, response) => { const result = await runEmployeeLifecycleReminderJobs(); await audit(request, 'LIFECYCLE_REMINDERS_RUN', 'ScheduledJob', request.auth!.sub, result); ok(response, result); }));
lifecycleRouter.get('/notifications', requirePermission('notification:hr:view'), asyncHandler(async (request, response) => { const { page, limit, skip } = pagination(request.query); const filter: any = { recipientRole: 'HR' }; if (request.query.unread === 'true') filter.readAt = null; const [items, total] = await Promise.all([Notification.find(filter).sort({ status: 1, dueDate: 1 }).skip(skip).limit(limit), Notification.countDocuments(filter)]); ok(response, items, { page, limit, total, pages: Math.ceil(total / limit) }); }));
lifecycleRouter.patch('/notifications/:id/read', requirePermission('notification:hr:view'), asyncHandler(async (request, response) => { const item = await Notification.findByIdAndUpdate(request.params.id, { readAt: new Date() }, { new: true }); if (!item) throw new ApiError(404, 'Notification not found', 'NOT_FOUND'); ok(response, item); }));
lifecycleRouter.post('/notifications/read-all', requirePermission('notification:hr:view'), asyncHandler(async (_request, response) => { const result = await Notification.updateMany({ recipientRole: 'HR', readAt: null }, { readAt: new Date() }); ok(response, { updated: result.modifiedCount }); }));

lifecycleRouter.get('/probation-evaluations', requirePermission('probation:view'), asyncHandler(async (request, response) => { const { page, limit, skip } = pagination(request.query); const filter: any = { 'employment.employmentType': 'PROBATION' }; if (request.auth!.role === 'MANAGER') filter['employment.reportingManager'] = request.auth!.employeeId; const search = String(request.query.search ?? '').trim(); if (search) filter.$or = [{ fullName: new RegExp(search, 'i') }, { employeeId: new RegExp(search, 'i') }]; const employees = await Employee.find(filter).populate('employment.department employment.designation employment.reportingManager', 'name fullName employeeId').sort({ 'employment.probationEndDate': 1 }).skip(skip).limit(limit); const items = await Promise.all(employees.map(async (employee: any) => { const evaluation = await ProbationEvaluation.findOne({ employee: employee._id, probationCycle: employee.employment.probationCycle ?? 1 }); const timing = employee.employment.probationEndDate ? reminderStatus(employee.employment.probationEndDate) : null; return { employee, evaluation, timing }; })); ok(response, items, { page, limit, total: await Employee.countDocuments(filter), pages: Math.ceil(await Employee.countDocuments(filter) / limit) }); }));

const evaluationInput = z.object({ ratings: z.array(z.object({ criterion: z.string().min(2).max(100), rating: z.number().int().min(1).max(5), comment: z.string().max(500).optional() })).min(1), strengths: z.string().max(2000).optional(), areasForImprovement: z.string().max(2000).optional(), managerComments: z.string().max(2000).optional(), hrComments: z.string().max(2000).optional(), recommendation: z.enum(['CONFIRM_PERMANENT', 'EXTEND_PROBATION', 'TERMINATE', 'OTHER']) });
lifecycleRouter.post('/probation-evaluations/:employeeId', requirePermission('probation:view'), asyncHandler(async (request, response) => { const input = evaluationInput.parse(request.body); const employee: any = await Employee.findById(request.params.employeeId); if (!employee || employee.employment.employmentType !== 'PROBATION') throw new ApiError(422, 'Employee is not on probation', 'NOT_PROBATION'); const isManager = request.auth!.role === 'MANAGER'; if (isManager && employee.employment.reportingManager?.toString() !== request.auth!.employeeId) throw new ApiError(403, 'Only the reporting manager can evaluate this employee', 'FORBIDDEN'); if (!isManager && !hrRoles.includes(request.auth!.role)) throw new ApiError(403, 'Evaluation is not permitted', 'FORBIDDEN'); const status = isManager ? 'PENDING_HR' : 'PENDING_FINAL'; const item = await ProbationEvaluation.findOneAndUpdate({ employee: employee._id, probationCycle: employee.employment.probationCycle ?? 1 }, { ...input, employee: employee._id, probationCycle: employee.employment.probationCycle ?? 1, evaluator: request.auth!.sub, evaluatorRole: request.auth!.role, status }, { upsert: true, new: true, runValidators: true }); employee.employment.probationEvaluationStatus = status; await employee.save(); await lifecycleEvent(employee._id, 'PROBATION_EVALUATED', request.auth!.sub, { newValue: { status, recommendation: input.recommendation }, metadata: { evaluationId: item._id } }); await audit(request, 'PROBATION_EVALUATION_SUBMITTED', 'ProbationEvaluation', item._id, { employee: employee._id, status, recommendation: input.recommendation }); ok(response, item, undefined, 201); }));

lifecycleRouter.post('/probation-evaluations/:id/finalize', requirePermission('probation:finalize'), asyncHandler(async (request, response) => { const input = z.object({ decision: z.enum(['CONFIRM_PERMANENT', 'EXTEND_PROBATION', 'TERMINATE', 'OTHER']), effectiveDate: z.coerce.date().default(() => new Date()), newProbationEndDate: z.coerce.date().optional(), reason: z.string().min(3).max(2000) }).parse(request.body); const evaluation: any = await ProbationEvaluation.findById(request.params.id); if (!evaluation) throw new ApiError(404, 'Evaluation not found', 'NOT_FOUND'); const employee: any = await Employee.findById(evaluation.employee); if (!employee) throw new ApiError(404, 'Employee not found', 'NOT_FOUND'); const previous = { employmentType: employee.employment.employmentType, probationEndDate: employee.employment.probationEndDate }; if (input.decision === 'CONFIRM_PERMANENT') { employee.employment.employmentType = 'PERMANENT'; employee.employment.confirmationDate = input.effectiveDate; employee.employment.probationEvaluationStatus = 'COMPLETED'; await lifecycleEvent(employee._id, 'PROBATION_CONFIRMED', request.auth!.sub, { previousValue: previous, newValue: { employmentType: 'PERMANENT', confirmationDate: input.effectiveDate }, reason: input.reason }); } else if (input.decision === 'EXTEND_PROBATION') { if (!input.newProbationEndDate || input.newProbationEndDate <= employee.employment.probationEndDate) throw new ApiError(422, 'A later probation end date is required', 'INVALID_EXTENSION_DATE'); employee.employment.probationEndDate = input.newProbationEndDate; employee.employment.probationEndDateSource = 'MANUAL_OVERRIDE'; employee.employment.probationCycle = (employee.employment.probationCycle ?? 1) + 1; employee.employment.probationEvaluationStatus = 'NOT_STARTED'; await lifecycleEvent(employee._id, 'PROBATION_EXTENDED', request.auth!.sub, { previousValue: previous, newValue: { probationEndDate: input.newProbationEndDate, probationCycle: employee.employment.probationCycle }, reason: input.reason }); } else { employee.employment.probationEvaluationStatus = 'COMPLETED'; await lifecycleEvent(employee._id, 'PROBATION_EVALUATED', request.auth!.sub, { previousValue: previous, newValue: { recommendation: input.decision }, reason: input.reason }); } await employee.save(); evaluation.status = 'COMPLETED'; evaluation.finalDecision = input.decision; evaluation.completedAt = new Date(); await evaluation.save(); await Notification.updateMany({ entityId: employee._id, type: 'PROBATION_EVALUATION_DUE', status: { $ne: 'COMPLETED' } }, { status: 'COMPLETED' }); await audit(request, 'PROBATION_EVALUATION_FINALIZED', 'ProbationEvaluation', evaluation._id, { employee: employee._id, decision: input.decision, reason: input.reason }); ok(response, { evaluation, employee }); }));

lifecycleRouter.post('/trainees/:id/convert', requirePermission('trainee:convert'), asyncHandler(async (request, response) => { const input = z.object({ employmentType: z.enum(['PROBATION', 'PERMANENT']), employeeId: z.string().min(3).max(30).transform((v) => v.toUpperCase()), probationStartDate: z.coerce.date().optional(), probationEndDate: z.coerce.date().optional(), reason: z.string().min(3).max(1000) }).parse(request.body); const employee: any = await Employee.findById(request.params.id); if (!employee || employee.employment.employmentType !== 'TRAINEE') throw new ApiError(422, 'Employee is not an active trainee', 'NOT_TRAINEE'); if (input.employmentType === 'PROBATION' && !input.probationStartDate) throw new ApiError(422, 'Probation start date is required', 'PROBATION_START_REQUIRED'); const previous = { employeeId: employee.employeeId, traineeId: employee.employment.traineeId, employmentType: 'TRAINEE' }; employee.employeeId = input.employeeId; employee.employment.originalTraineeId = employee.employment.originalTraineeId ?? employee.employment.traineeId; employee.employment.traineeStatus = 'CONVERTED'; employee.employment.employmentType = input.employmentType; if (input.employmentType === 'PROBATION') { const policy: any = await getHrPolicy(); employee.employment.probationStartDate = input.probationStartDate; employee.employment.probationEndDate = input.probationEndDate ?? addUtcMonths(input.probationStartDate!, policy.probationDurationMonths); employee.employment.probationEndDateSource = input.probationEndDate ? 'MANUAL_OVERRIDE' : 'AUTO_CALCULATED'; employee.employment.probationEvaluationStatus = 'NOT_STARTED'; } else employee.employment.confirmationDate = new Date(); await employee.save(); await lifecycleEvent(employee._id, 'TRAINEE_CONVERTED', request.auth!.sub, { previousValue: previous, newValue: { employeeId: employee.employeeId, employmentType: input.employmentType }, reason: input.reason }); await audit(request, 'TRAINEE_CONVERTED', 'Employee', employee._id, { previous, employeeId: employee.employeeId, employmentType: input.employmentType }); ok(response, employee); }));

lifecycleRouter.get('/employees/:id/history', requirePermission('employee:lifecycle:view'), asyncHandler(async (request, response) => ok(response, await EmployeeLifecycleEvent.find({ employee: request.params.id }).populate('performedBy', 'email').sort({ effectiveDate: -1 }))));
