'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { Building2, LockKeyhole, Mail } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { api } from '@/lib/api';

const schema = z.object({ email: z.email('Enter a valid work email'), password: z.string().min(8, 'Password must be at least 8 characters') });
type FormValues = z.infer<typeof schema>;

export default function LoginPage() {
  const router = useRouter(); const [serverError, setServerError] = useState('');
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { email: 'employee@demo.hrms.local', password: 'DemoPass123!' } });
  const submit = async (values: FormValues) => { setServerError(''); try { await api.post('/auth/login', values); router.push('/dashboard'); router.refresh(); } catch (error) { setServerError(error instanceof Error ? error.message : 'Unable to sign in'); } };
  return <main className="grid min-h-screen bg-white lg:grid-cols-[1.08fr_.92fr]"><section className="hidden bg-[#11263d] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-lg bg-[#2b91b8] text-xl font-bold">P</div><div><div className="text-xl font-bold">PeopleCore</div><div className="text-xs uppercase tracking-[.2em] text-slate-300">HR Management</div></div></div><div className="max-w-xl"><p className="mb-5 text-sm font-bold uppercase tracking-[.2em] text-[#55b8c7]">One workforce. One source of truth.</p><h1 className="text-5xl font-bold leading-tight">Workforce operations, without the noise.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-300">Secure employee records, auditable attendance, and clear leave approvals in one focused workspace.</p></div><div className="text-sm text-slate-400">Best Western Plus Runway · Internal system</div></section><section className="flex items-center justify-center bg-[#f6f8fa] p-5"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-lg bg-[#176b9c] text-lg font-bold text-white">P</div><div className="font-bold text-[#11263d]">PeopleCore HRMS</div></div></div><div className="card p-6 sm:p-8"><div className="mb-7 grid size-11 place-items-center rounded-lg bg-sky-50 text-[#176b9c]"><Building2 size={23}/></div><h2 className="text-2xl font-bold text-[#172b3d]">Welcome back</h2><p className="mt-2 text-sm text-slate-600">Sign in with your organisation account.</p><form className="mt-7 space-y-5" onSubmit={handleSubmit(submit)}><label className="block"><span className="mb-2 block text-sm font-semibold">Work email</span><div className="relative"><Mail className="absolute left-3 top-3 text-slate-400" size={18}/><input className="field field-with-icon" autoComplete="username" {...register('email')}/></div>{errors.email && <span className="mt-1 block text-xs text-red-600">{errors.email.message}</span>}</label><label className="block"><span className="mb-2 block text-sm font-semibold">Password</span><div className="relative"><LockKeyhole className="absolute left-3 top-3 text-slate-400" size={18}/><input className="field field-with-icon" type="password" autoComplete="current-password" {...register('password')}/></div>{errors.password && <span className="mt-1 block text-xs text-red-600">{errors.password.message}</span>}</label>{serverError && <div role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-700">{serverError}</div>}<button className="btn-primary w-full" disabled={isSubmitting}>{isSubmitting ? 'Signing in…' : 'Sign in'}</button></form><p className="mt-6 text-center text-xs leading-5 text-slate-500">Demo credentials are prefilled after running the development seed. Change all seeded passwords before any shared deployment.</p></div></div></section></main>;
}
