'use client';

import { ArrowLeft, Check } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useEffect, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { useAuth } from '@/features/auth/auth-provider';
import { api } from '@/lib/api';
import { EmployeeAdditionalFields } from './employee-additional-fields';

type Ref = { _id: string; name: string; code: string; active?: boolean };
type Manager = { _id: string; employeeId: string; fullName: string };
type Created = { _id: string };
export default function NewEmployeePage() {
  const router = useRouter();
  const { user } = useAuth();
  const [refs, setRefs] = useState<{ departments: Ref[]; designations: Ref[]; traineeTypes: Ref[]; locations: Ref[]; sections: Ref[]; managers: Manager[] }>({ departments: [], designations: [], traineeTypes: [], locations: [], sections: [], managers: [] });
  const [employmentType, setEmploymentType] = useState('PERMANENT');
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.get<Ref[]>('/organization/departments'), api.get<Ref[]>('/organization/designations'), api.get<Ref[]>('/lifecycle/trainee-types'), api.get<Ref[]>('/organization/locations'), api.get<Ref[]>('/organization/sections'), api.get<Manager[]>('/employees?limit=100')]).then(([departments, designations, traineeTypes, locations, sections, managers]) => setRefs({ departments, designations, traineeTypes, locations, sections, managers })).catch((reason) => setError(reason.message)); }, []);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const value = (name: string) => { const item = form.get(name); return typeof item === 'string' && item.trim() ? item.trim() : undefined; };
    const boolValue = (name: string) => value(name) === 'true' || form.get(name) === 'on';
    const address = (prefix: string) => ({ houseRoadVillage: value(`${prefix}HouseRoadVillage`), postOffice: value(`${prefix}PostOffice`), postCode: value(`${prefix}PostCode`), district: value(`${prefix}District`), upazila: value(`${prefix}Upazila`), line1: value(`${prefix}Line1`), country: value(`${prefix}Country`) || 'Bangladesh' });
    const emergencyContacts = [1, 2].map((index) => ({ name: value(`emergency${index}Name`), relationship: value(`emergency${index}Relationship`), address: value(`emergency${index}Address`), phone: value(`emergency${index}Phone`) })).filter((item) => item.name || item.phone);
    const family = [1, 2].map((index) => ({ name: value(`family${index}Name`), relationship: value(`family${index}Relationship`), occupation: value(`family${index}Occupation`), phone: value(`family${index}Phone`), dateOfBirth: value(`family${index}DateOfBirth`), anniversaryDate: value(`family${index}AnniversaryDate`), dependent: form.get(`family${index}Dependent`) === 'on' })).filter((item) => item.name || item.relationship);
    const identity = { nationalId: value('nationalId'), birthRegistrationNumber: value('birthRegistrationNumber'), eTin: value('eTin'), identificationMarks: value('identificationMarks'), passport: { number: value('passportNumber'), issueDate: value('passportIssueDate'), expiryDate: value('passportExpiryDate') }, visa: { number: value('visaNumber'), issueDate: value('visaIssueDate'), expiryDate: value('visaExpiryDate') }, workPermit: { startDate: value('workPermitStartDate'), endDate: value('workPermitEndDate') } };
    const bank = { bankName: value('bankName'), branchName: value('bankBranchName'), accountName: value('bankAccountName'), accountNumber: value('bankAccountNumber'), routingNumber: value('bankRoutingNumber'), accountType: value('bankAccountType'), mobileFinancialService: value('mobileFinancialService'), mobileAccountNumber: value('mobileAccountNumber') };
    setSaving(true); setError('');
    try {
      const employee = await api.post<Created>('/employees', {
        employeeId: value('employeeId'), title: value('title'), firstName: value('firstName'), middleName: value('middleName'), lastName: value('lastName'),
        personal: { fatherName: value('fatherName'), motherName: value('motherName'), dateOfBirth: value('dateOfBirth'), gender: value('gender'), bloodGroup: value('bloodGroup'), nationality: value('nationality'), religion: value('religion'), maritalStatus: value('maritalStatus'), heightCm: value('heightCm'), weightKg: value('weightKg'), specialSkills: value('specialSkills') },
        employment: { department: value('department'), section: value('section'), designation: value('designation'), employeeType: employmentType === 'PROBATION' ? 'PROBATIONARY' : employmentType, employmentType, joiningDate: value('joiningDate'), actualJoiningDate: value('actualJoiningDate'), status: value('status') || 'ACTIVE', locationRef: value('locationRef'), grade: value('grade'), traineeType: value('traineeType'), traineeStartDate: value('traineeStartDate'), expectedCompletionDate: value('expectedCompletionDate'), traineeRemarks: value('traineeRemarks'), traineeReminderDays: value('traineeReminderDays'), probationStartDate: value('probationStartDate'), probationEndDate: value('probationEndDate'), probationDurationMonths: value('probationDurationMonths'), probationReminderDays: value('probationReminderDays'), contractStartDate: value('contractStartDate'), contractEndDate: value('contractEndDate'), contractNotes: value('contractNotes'), contractReminderDays: value('contractReminderDays'), confirmationDate: value('confirmationDate'), reportingManager: value('reportingManager'), reviewer: value('reviewer'), employeeOf: value('employeeOf'), divisionName: value('divisionName'), businessUnit: value('businessUnit'), branch: value('branch'), workforceType: value('workforceType'), employeeCategory: value('employeeCategory'), jobDescription: value('jobDescription'), jobLevel: value('jobLevel'), employeeBand: value('employeeBand'), costCenter: value('costCenter'), approvedPositionId: value('approvedPositionId'), requisitionNo: value('requisitionNo'), joiningSource: value('joiningSource'), timeAttendanceApplicable: boolValue('timeAttendanceApplicable'), workShift: value('workShift'), dutySchedule: value('dutySchedule'), lockerNumber: value('lockerNumber'), dormitory: value('dormitory'), uniformApplicable: boolValue('uniformApplicable'), regionName: value('regionName'), clusterName: value('clusterName'), depotName: value('depotName'), territoryName: value('territoryName'), areaName: value('areaName'), otherErpId: value('otherErpId'), employmentRemarks: value('employmentRemarks') },
        profileData: { contact: { personalMobile: value('personalMobile'), officialMobile: value('officialMobile'), residentPhone: value('residentPhone'), personalEmail: value('personalEmail'), officialEmail: value('officialEmail'), presentAddress: address('present'), permanentAddress: address('permanent'), sameAsPresent: form.get('sameAsPresent') === 'on', emergencyContacts }, identity, family, bank: Object.values(bank).some(Boolean) ? bank : undefined },
      });
      router.push(`/employees/${employee._id}`);
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Employee could not be created'); setSaving(false); }
  }

  return <><PageHeader title="Create employee" description="Enter the employee's master and employment details on one scrollable page. Full name is generated from the name fields."/>
    {error && <div className="mb-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <form onSubmit={submit} className="card">
      <div className="border-b border-slate-200 p-5"><h2 className="font-bold">Employee information</h2><p className="mt-1 text-sm text-slate-500">Complete the required master and employment information below.</p></div>
      <div className="grid gap-4 p-5 sm:grid-cols-2">
        <label><span className="mb-1 block text-sm font-semibold">Employee ID</span><input name="employeeId" required={employmentType !== 'TRAINEE'} disabled={employmentType === 'TRAINEE'} className="field disabled:bg-slate-100" placeholder={employmentType === 'TRAINEE' ? 'Generated automatically' : 'EMP-000001'}/></label>
        <label><span className="mb-1 block text-sm font-semibold">Title</span><input name="title" className="field" placeholder="Mr / Ms / Dr"/></label>
        <label><span className="mb-1 block text-sm font-semibold">First name</span><input name="firstName" required className="field"/></label><label><span className="mb-1 block text-sm font-semibold">Middle name</span><input name="middleName" className="field"/></label><label><span className="mb-1 block text-sm font-semibold">Last name</span><input name="lastName" className="field"/></label>
        <label><span className="mb-1 block text-sm font-semibold">Employment type</span><select name="employmentType" value={employmentType} onChange={(event) => setEmploymentType(event.target.value)} className="field"><option value="PERMANENT">Permanent</option><option value="PROBATION">Probation</option><option value="CONTRACTUAL">Contractual</option><option value="TRAINEE">Trainee</option></select></label>
        <label><span className="mb-1 block text-sm font-semibold">Joining date</span><input name="joiningDate" type="date" required className="field"/></label>
        {employmentType === 'TRAINEE' && <><label><span className="mb-1 block text-sm font-semibold">Trainee type</span><select name="traineeType" required className="field"><option value="">Select...</option>{refs.traineeTypes.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label><span className="mb-1 block text-sm font-semibold">Trainee start date</span><input name="traineeStartDate" type="date" required className="field"/></label><label><span className="mb-1 block text-sm font-semibold">Expected completion</span><input name="expectedCompletionDate" type="date" className="field"/></label><label><span className="mb-1 block text-sm font-semibold">Reminder before completion (days)</span><input name="traineeReminderDays" type="number" min="0" max="180" className="field" placeholder="Use organization default"/></label><label className="sm:col-span-2"><span className="mb-1 block text-sm font-semibold">Trainee remarks</span><textarea name="traineeRemarks" className="field" rows={3}/></label></>}
        {employmentType === 'PROBATION' && <><label><span className="mb-1 block text-sm font-semibold">Probation start</span><input name="probationStartDate" type="date" required className="field"/></label><label><span className="mb-1 block text-sm font-semibold">Probation duration (months)</span><input name="probationDurationMonths" type="number" min="1" max="36" className="field" placeholder="Use organization default"/></label><label><span className="mb-1 block text-sm font-semibold">Probation end override</span><input name="probationEndDate" type="date" className="field"/><span className="mt-1 block text-xs text-slate-500">Leave blank to calculate it from the employee duration.</span></label><label><span className="mb-1 block text-sm font-semibold">Reminder before end (days)</span><input name="probationReminderDays" type="number" min="0" max="180" className="field" placeholder="Use organization default"/></label></>}
        {employmentType === 'CONTRACTUAL' && <><label><span className="mb-1 block text-sm font-semibold">Contract start</span><input name="contractStartDate" type="date" required className="field"/></label><label><span className="mb-1 block text-sm font-semibold">Contract end</span><input name="contractEndDate" type="date" required className="field"/></label><label><span className="mb-1 block text-sm font-semibold">Reminder before expiry (days)</span><input name="contractReminderDays" type="number" min="0" max="365" className="field" placeholder="Use organization default"/></label><label className="sm:col-span-2"><span className="mb-1 block text-sm font-semibold">Contract notes</span><textarea name="contractNotes" className="field" rows={3}/></label></>}
        {employmentType === 'PERMANENT' && <label><span className="mb-1 block text-sm font-semibold">Confirmation date</span><input name="confirmationDate" type="date" className="field"/></label>}
        <label><span className="mb-1 block text-sm font-semibold">Department</span><select name="department" required className="field"><option value="">Select…</option>{refs.departments.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label>
        <label><span className="mb-1 block text-sm font-semibold">Designation</span><select name="designation" required className="field"><option value="">Select…</option>{refs.designations.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label>
        <label><span className="mb-1 block text-sm font-semibold">Grade</span><input name="grade" className="field"/></label>
        <label><span className="mb-1 flex items-center justify-between gap-3 text-sm font-semibold"><span>Location</span>{user && ['SUPER_ADMIN', 'HR_ADMIN'].includes(user.role) && <Link href="/administration/locations" className="text-xs font-medium text-[#176b9c] hover:underline">Manage locations</Link>}</span><select name="locationRef" required className="field"><option value="">Select...</option>{refs.locations.filter((item) => item.active !== false).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label>
        <EmployeeAdditionalFields sections={refs.sections} managers={refs.managers} userRole={user?.role}/>
        <div className="sm:col-span-2 rounded-md border border-sky-200 bg-sky-50 p-4 text-sm text-sky-800">All information on this page is saved with the employee record. Payroll is intentionally excluded for now; login access is provisioned separately.</div>
      </div>
      <div className="flex justify-between border-t border-slate-200 p-5"><Link href="/employees" className="btn-secondary inline-flex items-center gap-2"><ArrowLeft size={16}/>Cancel</Link><button className="btn-primary flex items-center gap-2" disabled={saving}>{saving ? 'Creating...' : 'Create employee'}<Check size={16}/></button></div>
    </form></>;
}
