'use client';

import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { StatusBadge } from '@/components/status-badge';
import { api } from '@/lib/api';

interface User{_id:string;email:string;role:string;status:string;employee?:{employeeId:string;fullName:string}}
interface Log{_id:string;timestamp:string;actor?:{email:string};action:string;entityType:string;entityId:string}
export default function AdministrationPage(){const [tab,setTab]=useState<'users'|'audit'>('users');const [users,setUsers]=useState<User[]>([]);const [logs,setLogs]=useState<Log[]>([]);const [error,setError]=useState('');useEffect(()=>{Promise.all([api.get<User[]>('/users'),api.get<Log[]>('/audit?limit=50')]).then(([u,l])=>{setUsers(u);setLogs(l)}).catch(e=>setError(e.message))},[]);return <><PageHeader title="Administration" description="System access is separate from employee records; important changes are auditable."/>{error&&<div className="mb-4 rounded-md bg-red-50 p-3 text-red-700">{error}</div>}<div className="mb-4 flex gap-2"><button className={tab==='users'?'btn-primary':'btn-secondary'} onClick={()=>setTab('users')}>Users & roles</button><button className={tab==='audit'?'btn-primary':'btn-secondary'} onClick={()=>setTab('audit')}>Audit log</button></div><div className="card table-wrap">{tab==='users'?<table><thead><tr><th>User</th><th>Linked employee</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(user=><tr key={user._id}><td className="font-semibold">{user.email}</td><td>{user.employee?<><b>{user.employee.fullName}</b><div className="text-xs text-slate-500">{user.employee.employeeId}</div></>:'Not linked'}</td><td>{user.role.replaceAll('_',' ')}</td><td><StatusBadge value={user.status}/></td></tr>)}</tbody></table>:<table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th></tr></thead><tbody>{logs.map(log=><tr key={log._id}><td>{new Date(log.timestamp).toLocaleString()}</td><td>{log.actor?.email??'System'}</td><td className="font-semibold">{log.action.replaceAll('_',' ')}</td><td>{log.entityType}<div className="text-xs text-slate-500">{log.entityId}</div></td></tr>)}</tbody></table>}</div></>}
