'use client';

import { Search, X } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { StatusBadge } from '@/components/status-badge';
import { api } from '@/lib/api';

type Item = { employee: { _id: string; employeeId: string; fullName: string; employment: { department?: { name: string }; designation?: { name: string }; reportingManager?: { fullName: string }; joiningDate: string; probationStartDate?: string; probationEndDate?: string; probationEvaluationStatus?: string } }; evaluation?: { _id: string; status: string; recommendation: string }; timing?: { days: number; status: string } };
const criteria = ['Attendance / Punctuality', 'Work Quality', 'Job Knowledge', 'Communication', 'Teamwork', 'Discipline', 'Learning Ability', 'Initiative', 'Overall Performance'];
export default function ProbationEvaluationsPage() {
  const [items, setItems] = useState<Item[]>([]); const [tab, setTab] = useState('DUE_SOON'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<Item | null>(null); const [message, setMessage] = useState('');
  const load = () => api.get<Item[]>(`/lifecycle/probation-evaluations?search=${encodeURIComponent(search)}&limit=100`).then(setItems).catch((error) => setMessage(error.message));
  useEffect(() => { void load(); }, []);
  const visible = items.filter((item) => tab === 'COMPLETED' ? item.evaluation?.status === 'COMPLETED' : item.evaluation?.status !== 'COMPLETED' && item.timing?.status === tab);
  async function evaluate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); try { await api.post(`/lifecycle/probation-evaluations/${selected.employee._id}`, { ratings: criteria.map((criterion, index) => ({ criterion, rating: Number(form.get(`rating-${index}`)) })), strengths: form.get('strengths'), areasForImprovement: form.get('areasForImprovement'), managerComments: form.get('managerComments'), hrComments: form.get('hrComments'), recommendation: form.get('recommendation') }); setSelected(null); setMessage('Evaluation submitted.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Evaluation failed'); } }
  async function finalize(item: Item) { if (!item.evaluation) return; const decision = window.prompt('Final decision: CONFIRM_PERMANENT, EXTEND_PROBATION, TERMINATE, or OTHER', item.evaluation.recommendation); if (!decision) return; const reason = window.prompt('Decision reason (required)'); if (!reason) return; const newProbationEndDate = decision === 'EXTEND_PROBATION' ? window.prompt('New probation end date (YYYY-MM-DD)') : undefined; try { await api.post(`/lifecycle/probation-evaluations/${item.evaluation._id}/finalize`, { decision, reason, newProbationEndDate: newProbationEndDate || undefined }); setMessage('Final decision recorded.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Finalization failed'); } }
  return <><PageHeader title="Probation evaluations" description="Database-derived reviews, reminders, and final employment decisions."/>{message && <div className="mb-4 rounded-md bg-sky-50 p-3 text-sm text-sky-800">{message}</div>}<div className="mb-4 flex flex-wrap gap-2">{['DUE_SOON','DUE_TODAY','OVERDUE','COMPLETED'].map((value) => <button key={value} className={tab === value ? 'btn-primary' : 'btn-secondary'} onClick={() => setTab(value)}>{value.replaceAll('_',' ')}</button>)}</div><section className="card"><div className="border-b border-slate-200 p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="field pl-10" value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Search employee"/></div></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Manager</th><th>Probation period</th><th>Timing</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map((item) => <tr key={item.employee._id}><td><b>{item.employee.fullName}</b><div className="text-xs text-slate-500">{item.employee.employeeId}</div></td><td>{item.employee.employment.department?.name ?? '—'}<div className="text-xs text-slate-500">{item.employee.employment.designation?.name}</div></td><td>{item.employee.employment.reportingManager?.fullName ?? '—'}</td><td>{item.employee.employment.probationStartDate ? new Date(item.employee.employment.probationStartDate).toLocaleDateString() : '—'} – {item.employee.employment.probationEndDate ? new Date(item.employee.employment.probationEndDate).toLocaleDateString() : '—'}</td><td><StatusBadge value={item.timing?.status ?? 'UNSCHEDULED'}/><div className="mt-1 text-xs text-slate-500">{item.timing ? item.timing.days < 0 ? `${Math.abs(item.timing.days)} days overdue` : `${item.timing.days} days remaining` : ''}</div></td><td>{item.evaluation?.status ?? item.employee.employment.probationEvaluationStatus ?? 'NOT_STARTED'}</td><td className="space-x-2"><button className="text-sm font-semibold text-[#176b9c]" onClick={() => setSelected(item)}>Evaluate</button>{item.evaluation?.status === 'PENDING_FINAL' && <button className="text-sm font-semibold text-emerald-700" onClick={() => void finalize(item)}>Finalize</button>}</td></tr>)}{visible.length === 0 && <tr><td colSpan={7} className="py-12 text-center text-slate-500">No evaluations in this category.</td></tr>}</tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-4"><form onSubmit={evaluate} className="card mx-auto my-8 max-w-3xl"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h2 className="font-bold">Evaluate {selected.employee.fullName}</h2><p className="text-sm text-slate-500">Rate each criterion from 1 to 5.</p></div><button type="button" onClick={() => setSelected(null)}><X size={20}/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2">{criteria.map((criterion, index) => <label key={criterion}><span className="mb-1 block text-sm font-semibold">{criterion}</span><select name={`rating-${index}`} className="field" defaultValue="3">{[1,2,3,4,5].map((rating) => <option key={rating}>{rating}</option>)}</select></label>)}<label className="sm:col-span-2"><span className="mb-1 block text-sm font-semibold">Strengths</span><textarea name="strengths" className="field" rows={2}/></label><label className="sm:col-span-2"><span className="mb-1 block text-sm font-semibold">Areas for improvement</span><textarea name="areasForImprovement" className="field" rows={2}/></label><label><span className="mb-1 block text-sm font-semibold">Manager comments</span><textarea name="managerComments" className="field" rows={3}/></label><label><span className="mb-1 block text-sm font-semibold">HR comments</span><textarea name="hrComments" className="field" rows={3}/></label><label className="sm:col-span-2"><span className="mb-1 block text-sm font-semibold">Recommendation</span><select name="recommendation" className="field"><option>CONFIRM_PERMANENT</option><option>EXTEND_PROBATION</option><option>TERMINATE</option><option>OTHER</option></select></label></div><div className="flex justify-end gap-3 border-t border-slate-200 p-5"><button type="button" className="btn-secondary" onClick={() => setSelected(null)}>Cancel</button><button className="btn-primary">Submit evaluation</button></div></form></div>}
  </>;
}
