'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { StatusBadge } from '@/components/status-badge';
import { api } from '@/lib/api';

type Employee = { _id: string; employeeId: string; fullName: string; candidateId?: string; title?: string; personal?: Record<string, unknown> & { phone?: string; personalEmail?: string; dateOfBirth?: string; bloodGroup?: string }; employment: Record<string, unknown> & { department?: { name: string }; section?: { name: string }; designation?: { name: string }; locationRef?: { name: string }; reportingManager?: { fullName: string }; reviewer?: { fullName: string }; traineeType?: { name: string }; employmentType?: string; employeeType: string; traineeId?: string; originalTraineeId?: string; traineeStatus?: string; probationEndDate?: string; confirmationDate?: string; status: string; joiningDate: string; location?: string; grade?: string } };
type Contact = { personalMobile?: string; officialMobile?: string; residentPhone?: string; personalEmail?: string; officialEmail?: string; presentAddress?: Record<string, string>; permanentAddress?: Record<string, string>; emergencyContacts?: Array<{ name?: string; relationship?: string; address?: string; phone?: string }> };
type Family = { _id: string; name: string; relationship: string; occupation?: string; phone?: string; dateOfBirth?: string; anniversaryDate?: string; dependent?: boolean };
type Bank = { bankName?: string; branchName?: string; accountName?: string; accountNumber?: string; routingNumber?: string; accountType?: string; mobileFinancialService?: string; mobileAccountNumber?: string };
type ProfileData = { contact?: Contact; identity?: Record<string, unknown>; bank?: Bank; family: Family[]; education: unknown[]; experience: unknown[]; identityRestricted: boolean; bankRestricted: boolean };
const tabs = ['Overview', 'Personal', 'Employment', 'Organization', 'Contact', 'Family', 'Emergency', 'Identity', 'Bank', 'Education', 'Experience', 'Documents', 'Attendance', 'Leave', 'Benefits', 'Assets', 'Performance', 'Training', 'Audit history'];

function InfoGrid({ title, items }: { title: string; items: Array<[string, unknown]> }) {
  return <section className="card p-5"><h2 className="font-bold">{title}</h2><dl className="mt-4 grid gap-x-6 sm:grid-cols-2">{items.map(([label, value]) => <div key={label} className="border-b border-slate-100 py-3"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium">{value === true ? 'Yes' : value === false ? 'No' : String(value || '—')}</dd></div>)}</dl></section>;
}

export default function EmployeeDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [employee, setEmployee] = useState<Employee | null>(null); const [profile, setProfile] = useState<ProfileData | null>(null); const [tab, setTab] = useState('Overview'); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.get<Employee>(`/employees/${id}`), api.get<ProfileData>(`/employees/${id}/profile-data`)]).then(([record, data]) => { setEmployee(record); setProfile(data); }).catch((reason) => setError(reason.message)); }, [id]);
  if (error) return <div className="rounded-md bg-red-50 p-4 text-red-700">{error}</div>;
  if (!employee) return <div className="card h-64 animate-pulse bg-slate-100"/>;
  const rows = [
    [employee.employment.traineeId ? 'Trainee ID' : 'Employee ID', employee.employment.traineeId ?? employee.employeeId], ['Employment type', employee.employment.employmentType ?? 'Manual review required'], ['Employment status', employee.employment.status], ['Trainee category', employee.employment.traineeType?.name], ['Department', employee.employment.department?.name], ['Designation', employee.employment.designation?.name], ['Joining date', new Date(employee.employment.joiningDate).toLocaleDateString()], ['Probation ends', employee.employment.probationEndDate ? new Date(employee.employment.probationEndDate).toLocaleDateString() : undefined], ['Confirmed', employee.employment.confirmationDate ? new Date(employee.employment.confirmationDate).toLocaleDateString() : undefined], ['Location', employee.employment.locationRef?.name ?? employee.employment.location], ['Reporting manager', employee.employment.reportingManager?.fullName],
  ];
  const personal = employee.personal ?? {};
  const employment = employee.employment;
  const identity = (profile?.identity ?? {}) as { nationalId?: string; birthRegistrationNumber?: string; eTin?: string; identificationMarks?: string; passport?: { number?: string; issueDate?: string; expiryDate?: string }; visa?: { number?: string; issueDate?: string; expiryDate?: string }; workPermit?: { startDate?: string; endDate?: string } };
  const addressText = (address?: Record<string, string>) => address ? Object.values(address).filter(Boolean).join(', ') : undefined;
  return <><PageHeader title={employee.fullName} description={`${employee.employeeId} · ${employee.employment.designation?.name ?? 'Designation not assigned'}`} action={<Link href={`/employees/${id}/edit`} className="btn-primary">Edit employee</Link>}/>
    <div className="mb-5 flex flex-wrap items-center gap-3 rounded-lg border border-slate-200 bg-white p-4"><div className="grid size-14 place-items-center rounded-full bg-sky-50 text-xl font-bold text-[#176b9c]">{employee.fullName.charAt(0)}</div><div><div className="font-bold">{employee.title ? `${employee.title} ` : ''}{employee.fullName}</div><div className="mt-1"><StatusBadge value={employee.employment.status}/></div></div></div>
    <div className="mb-5 overflow-x-auto border-b border-slate-200"><div className="flex min-w-max gap-1">{tabs.map((item) => <button key={item} className={`border-b-2 px-3 py-3 text-sm font-semibold ${tab === item ? 'border-[#176b9c] text-[#176b9c]' : 'border-transparent text-slate-500 hover:text-slate-800'}`} onClick={() => setTab(item)}>{item}</button>)}</div></div>
    {tab === 'Overview' && <div className="grid gap-5 lg:grid-cols-2"><section className="card p-5"><h2 className="font-bold">Employee summary</h2><dl className="mt-4 grid grid-cols-2 gap-x-4">{rows.map(([label, value]) => <div className="contents" key={label}><dt className="border-b border-slate-100 py-3 text-sm text-slate-500">{label}</dt><dd className="border-b border-slate-100 py-3 text-sm font-semibold">{value || '—'}</dd></div>)}</dl></section><section className="card p-5"><h2 className="font-bold">Profile records</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Contact profile</dt><dd className="font-semibold">{profile?.contact ? 'Available' : 'Not completed'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Family members</dt><dd className="font-semibold">{profile?.family.length ?? 0}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Education records</dt><dd className="font-semibold">{profile?.education.length ?? 0}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Experience records</dt><dd className="font-semibold">{profile?.experience.length ?? 0}</dd></div></dl></section></div>}
    {tab === 'Personal' && <InfoGrid title="Personal information" items={[["Father's name", personal.fatherName], ["Mother's name", personal.motherName], ['Date of birth', personal.dateOfBirth ? new Date(String(personal.dateOfBirth)).toLocaleDateString() : undefined], ['Gender', personal.gender], ['Blood group', personal.bloodGroup], ['Nationality', personal.nationality], ['Religion', personal.religion], ['Marital status', personal.maritalStatus], ['Height (cm)', personal.heightCm], ['Weight (kg)', personal.weightKg], ['Special training / skills', personal.specialSkills]]}/>}
    {tab === 'Employment' && <InfoGrid title="Employment information" items={[["Employment type", employment.employmentType], ['Employee category', employment.employeeCategory], ['Workforce type', employment.workforceType], ['Joining date', new Date(employment.joiningDate).toLocaleDateString()], ['Actual joining date', employment.actualJoiningDate ? new Date(String(employment.actualJoiningDate)).toLocaleDateString() : undefined], ['Confirmation date', employment.confirmationDate ? new Date(employment.confirmationDate).toLocaleDateString() : undefined], ['Grade', employment.grade], ['Job level', employment.jobLevel], ['Employee band', employment.employeeBand], ['Job description', employment.jobDescription], ['Duty schedule', employment.dutySchedule], ['Shift', employment.workShift], ['Attendance applicable', employment.timeAttendanceApplicable], ['Uniform applicable', employment.uniformApplicable], ['Locker number', employment.lockerNumber], ['Dormitory', employment.dormitory], ['Remarks', employment.employmentRemarks]]}/>}
    {tab === 'Organization' && <InfoGrid title="Organization assignment" items={[["Employee of", employment.employeeOf], ['Business unit', employment.businessUnit], ['Division', employment.divisionName], ['Branch', employment.branch], ['Department', employment.department?.name], ['Section', employment.section?.name], ['Designation', employment.designation?.name], ['Location', employment.locationRef?.name ?? employment.location], ['Cost center', employment.costCenter], ['Supervisor', employment.reportingManager?.fullName], ['Reviewer / HOD', employment.reviewer?.fullName], ['Approved position ID', employment.approvedPositionId], ['Requisition no.', employment.requisitionNo], ['Joining source', employment.joiningSource], ['Region', employment.regionName], ['Cluster', employment.clusterName], ['Depot', employment.depotName], ['Territory', employment.territoryName], ['Area', employment.areaName], ['Other ERP ID', employment.otherErpId]]}/>}
    {tab === 'Contact' && <InfoGrid title="Contact information" items={[["Personal mobile", profile?.contact?.personalMobile], ['Official mobile', profile?.contact?.officialMobile], ['Resident phone', profile?.contact?.residentPhone], ['Personal email', profile?.contact?.personalEmail], ['Official email', profile?.contact?.officialEmail], ['Present address', addressText(profile?.contact?.presentAddress)], ['Permanent address', addressText(profile?.contact?.permanentAddress)]]}/>}
    {tab === 'Family' && <section className="card table-wrap"><table><thead><tr><th>Name</th><th>Relationship</th><th>Occupation</th><th>Phone</th><th>Dependent</th></tr></thead><tbody>{profile?.family.map((member) => <tr key={member._id}><td className="font-semibold">{member.name}</td><td>{member.relationship}</td><td>{member.occupation || '—'}</td><td>{member.phone || '—'}</td><td>{member.dependent ? 'Yes' : 'No'}</td></tr>)}{!profile?.family.length && <tr><td colSpan={5} className="py-10 text-center text-slate-500">No family records.</td></tr>}</tbody></table></section>}
    {tab === 'Emergency' && <section className="grid gap-4 md:grid-cols-2">{profile?.contact?.emergencyContacts?.map((contact, index) => <div key={`${contact.name}-${index}`} className="card p-5"><h2 className="font-bold">{contact.name}</h2><p className="mt-1 text-sm text-slate-500">{contact.relationship || 'Relationship not provided'}</p><p className="mt-4 text-sm font-semibold">{contact.phone}</p><p className="mt-1 text-sm text-slate-600">{contact.address}</p></div>)}{!profile?.contact?.emergencyContacts?.length && <div className="card p-8 text-center text-slate-500">No emergency contacts.</div>}</section>}
    {tab === 'Identity' && (profile?.identityRestricted ? <section className="card p-8 text-center text-slate-500">Sensitive identity details are restricted for your role.</section> : <InfoGrid title="Identity information" items={[["National ID", identity.nationalId], ['Birth registration', identity.birthRegistrationNumber], ['E-TIN', identity.eTin], ['Passport number', identity.passport?.number], ['Passport issue date', identity.passport?.issueDate ? new Date(identity.passport.issueDate).toLocaleDateString() : undefined], ['Passport expiry date', identity.passport?.expiryDate ? new Date(identity.passport.expiryDate).toLocaleDateString() : undefined], ['Visa number', identity.visa?.number], ['Work permit start', identity.workPermit?.startDate ? new Date(identity.workPermit.startDate).toLocaleDateString() : undefined], ['Work permit end', identity.workPermit?.endDate ? new Date(identity.workPermit.endDate).toLocaleDateString() : undefined], ['Identification marks', identity.identificationMarks]]}/>)}
    {tab === 'Bank' && (profile?.bankRestricted ? <section className="card p-8 text-center text-slate-500">Bank information is restricted to Super Admin and HR Admin.</section> : <InfoGrid title="Bank information" items={[["Bank name", profile?.bank?.bankName], ['Branch', profile?.bank?.branchName], ['Account name', profile?.bank?.accountName], ['Account number', profile?.bank?.accountNumber], ['Routing number', profile?.bank?.routingNumber], ['Account type', profile?.bank?.accountType], ['Mobile financial service', profile?.bank?.mobileFinancialService], ['Mobile account number', profile?.bank?.mobileAccountNumber]]}/>)}
    {!['Overview', 'Personal', 'Employment', 'Organization', 'Contact', 'Family', 'Emergency', 'Identity', 'Bank'].includes(tab) && <section className="card p-8 text-center"><h2 className="font-bold">{tab}</h2><p className="mt-2 text-sm text-slate-500">No records are available in this section yet.</p></section>}
  </>;
}
