'use client';

import { Plus } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { StatusBadge } from '@/components/status-badge';
import { api } from '@/lib/api';

interface Item { _id:string; name:string; code:string; active:boolean; description?:string }
export default function OrganizationPage(){const [tab,setTab]=useState<'departments'|'designations'>('departments');const [items,setItems]=useState<Item[]>([]);const [error,setError]=useState('');const load=()=>api.get<Item[]>(`/organization/${tab}`).then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[tab]);const create=async(form:FormData)=>{try{await api.post(`/organization/${tab}`,{name:form.get('name'),code:form.get('code'),active:true});await load();(document.getElementById('org-form') as HTMLFormElement)?.reset()}catch(e){setError(e instanceof Error?e.message:'Could not save')}};return <><PageHeader title="Organization" description="Controlled departments and designations referenced by employee records."/><div className="mb-4 flex gap-2">{(['departments','designations'] as const).map(value=><button key={value} className={tab===value?'btn-primary':'btn-secondary'} onClick={()=>setTab(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>{error&&<div className="mb-4 rounded-md bg-red-50 p-3 text-red-700">{error}</div>}<div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="card table-wrap"><table><thead><tr><th>Name</th><th>Code</th><th>Status</th></tr></thead><tbody>{items.map(item=><tr key={item._id}><td className="font-semibold">{item.name}</td><td>{item.code}</td><td><StatusBadge value={item.active?'ACTIVE':'INACTIVE'}/></td></tr>)}</tbody></table></div><form id="org-form" action={create} className="card h-fit space-y-4 p-5"><div className="flex items-center gap-2 font-bold"><Plus size={18}/>Add {tab==='departments'?'department':'designation'}</div><label className="block"><span className="mb-1 block text-sm font-semibold">Name</span><input name="name" required className="field"/></label><label className="block"><span className="mb-1 block text-sm font-semibold">Code</span><input name="code" required className="field uppercase"/></label><button className="btn-primary w-full">Save</button></form></div></>}
